// app/layout.jsx


// SEO Metadata
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root layout component
export default function RootLayout({ children }) {
  return (
    <>
      {children}
    </>
  );
}
