import mongoose, { Schema, models, model } from "mongoose";

const userBioSchema = new Schema({
  Id: { type: String, required: true, unique: true },
  Image: { type: String, default: "" },
  Name: { type: String, default: "" },
  Bio: { type: String, default: "" },
  enableFollowButton: { type: Boolean, default: false },
  emailVerification: { type: Boolean, default: false },
  phoneVerification: { type: Boolean, default: false },
  thankTitle: { type: String, default: "" },
  titleDescription: { type: String, default: "" },
  enableGiftButton: { type: Boolean, default: false },
  giftTitle: { type: String, default: "" },
  gift: { type: String, default: "" },
  showContactDetails: { type: Boolean, default: false },
  bookingEnabled: { type: Boolean, default: false },
  showEmail: { type: Boolean, default: false },
  showPhone: { type: Boolean, default: false },
  email: { type: String, default: "" },
  phone: { type: String, default: "" },

  // Social Links
  "App Store": { type: String, default: "" },
  "Apple Music": { type: String, default: "" },
  "Apple Podcasts": { type: String, default: "" },
  Behance: { type: String, default: "" },
  Clubhouse: { type: String, default: "" },
  Discord: { type: String, default: "" },
  Email: { type: String, default: "" },
  GitHub: { type: String, default: "" },
  LinkedIn: { type: String, default: "" },
  Patreon: { type: String, default: "" },
  Pinterest: { type: String, default: "" },
  "Play Store": { type: String, default: "" },
  Snapchat: { type: String, default: "" },
  Spotify: { type: String, default: "" },
  Substack: { type: String, default: "" },
  Threads: { type: String, default: "" },
  TikTok: { type: String, default: "" },
  Twitch: { type: String, default: "" },
  Twitter: { type: String, default: "" },
  WhatsApp: { type: String, default: "" },
  YouTube: { type: String, default: "" },
  Instagram: { type: String, default: "" },
  Facebook: { type: String, default: "" },
});

export const UserBio = models.UserBio || model("UserBio", userBioSchema);
